apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
        - name: mysql-pod
          image: docker-virtual.artifactory.igentify.net/mysql:8.0.13
          args:
            - "--default-authentication-plugin=mysql_native_password"
          ports: 
            - containerPort: 3306
              hostPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
          
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql-svc
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 32306
    name: http
  selector:
    app: mysql-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-deployment
  template:
    metadata:
      labels:
        app: phpmyadmin-deployment
    spec:
      containers:
        - name: phpmyadmin-pod
          image: docker-virtual.artifactory.igentify.net/phpmyadmin/phpmyadmin:4.8
          ports: 
            - containerPort: 80
          env:
          - name: PMA_HOST
            value: "mysql-svc.default.svc.cluster.local"
          - name: PMA_PORT
            value: "3306"
          - name: PMA_USER
            value: "root"
          - name: PMA_PASSWORD
            value: "123456"
      imagePullSecrets:
      - name: regcred
          
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  labels:
    app: phpmyadmin-svc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32082
    name: http
  selector:
    app: phpmyadmin-deployment