# Selenium Hub
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
spec:
  selector:
    matchLabels:
      app: selenium-hub
  replicas: 1
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:3.13.0-argon
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4444
          hostPort: 4444
---

apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  ports:
    - port: 4444
      nodePort: 30000
  type: NodePort
  selector:
    app: selenium-hub

---

# Selenium Chrome
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome
spec:
  selector:
    matchLabels:
      app: selenium-chrome
  replicas: 1
  template:
    metadata:
      labels:
        app: selenium-chrome
    spec:
      containers:
      - name: selenium-chrome
        image: selenium/node-chrome:3.13.0-argon
        imagePullPolicy: IfNotPresent
        env:
          - name: HUB_HOST
            value: selenium-hub
