# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

current_dir = File.dirname(File.expand_path('../../',__FILE__))
configs = YAML.load_file("#{current_dir}/config.yml")
vagrant_config = configs['configs']

Vagrant.configure("2") do |config|
  config.vm.define "selenium" do |machine|
    machine.vm.provider 'virtualbox' do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = '2048'
      vb.cpus = 2
    end
    machine.vm.box = 'ubuntu/xenial64'
    machine.vm.hostname = 'selenium'
    machine.vm.network 'private_network', ip: "#{vagrant_config['base-ip']}.33"

    machine.vm.provision "chef_solo" do |chef|
      chef.add_recipe "k8s"
      chef.cookbooks_path = ["cookbooks"]
    end

    # #create configMap - Run Once
    # machine.vm.provision "shell", inline: $serviceScript

    # Taint the master to run pods on it
    machine.vm.provision "shell", run: "always" do |s|
      s.inline = "kubectl taint node selenium node-role.kubernetes.io/master-"
    end

    # Create the selenium deployments
    #Apply the deployments - Ruh always
    machine.vm.provision "shell", run: "always" do |s|
      s.inline = "kubectl apply -f /vagrant/environment/selenium/selenium.yml"
    end


  end

end
